CREATE DATABASE IF NOT EXISTS bounty_list
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'bounty'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_STRONG_DB_PASSWORD';

ALTER USER 'bounty'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_STRONG_DB_PASSWORD';

GRANT ALL PRIVILEGES ON bounty_list.* TO 'bounty'@'127.0.0.1';
FLUSH PRIVILEGES;